---
name: "Default Workflow"

schedules:
  - cron: "0 */6 * * *"
    branches:
      include:
        - main
    always: true

variables:
  - group: credentials

pool:
  vmImage: ubuntu-latest

jobs:

  - job: Job
    displayName: "Job"
    steps:

      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - task: Bash@3
        displayName: "Bash"
        inputs:
          targetType: "inline"
          script: |
            echo Bash

      - task: PowerShell@2
        displayName: "PowerShell"
        inputs:
          targetType: "inline"
          script: |
            echo PowerShell
